import { VocabItem } from '../types';

export const SAMPLE_VOCABULARY: VocabItem[] = [
  // NOMS
  {
    id: '1',
    category: 'NOMS',
    frenchText: 'Addition / Facture',
    englishText: 'Bill / Invoice',
    arabicText: 'الفاتورة',
    sourceText: 'Addition / Facture | Bill / Invoice | الفاتورة',
    germanText: 'die Rechnung',
    article: 'die',
  },
  {
    id: '2',
    category: 'NOMS',
    frenchText: 'Ami',
    englishText: 'Friend',
    arabicText: 'صديق',
    sourceText: 'Ami | Friend | صديق',
    germanText: 'der Freund',
    article: 'der',
  },
  {
    id: '3',
    category: 'NOMS',
    frenchText: 'Animal de compagnie',
    englishText: 'Pet',
    arabicText: 'حيوان أليف',
    sourceText: 'Animal de compagnie | Pet | حيوان أليف',
    germanText: 'das Haustier',
    article: 'das',
  },
  {
    id: '4',
    category: 'NOMS',
    frenchText: 'Art',
    englishText: 'Art',
    arabicText: 'فن',
    sourceText: 'Art | Art | فن',
    germanText: 'die Kunst',
    article: 'die',
  },
  {
    id: '5',
    category: 'NOMS',
    frenchText: 'Bibliothèque',
    englishText: 'Library',
    arabicText: 'مكتبة',
    sourceText: 'Bibliothèque | Library | مكتبة',
    germanText: 'die Bibliothek',
    article: 'die',
  },
  {
    id: '6',
    category: 'NOMS',
    frenchText: 'Biscuit',
    englishText: 'Cookie / Biscuit',
    arabicText: 'بسكويت',
    sourceText: 'Biscuit | Cookie | بسكويت',
    germanText: 'der Keks',
    article: 'der',
  },
  {
    id: '7',
    category: 'NOMS',
    frenchText: 'Boulanger',
    englishText: 'Baker (m)',
    arabicText: 'خباز',
    sourceText: 'Boulanger | Baker | خباز',
    germanText: 'der Bäcker',
    article: 'der',
  },
  {
    id: '8',
    category: 'NOMS',
    frenchText: 'Boulangère',
    englishText: 'Baker (f)',
    arabicText: 'خبازة',
    sourceText: 'Boulangère | Baker (f) | خبازة',
    germanText: 'die Bäckerin',
    article: 'die',
  },
  {
    id: '9',
    category: 'NOMS',
    frenchText: 'Boulangerie',
    englishText: 'Bakery',
    arabicText: 'مخبز',
    sourceText: 'Boulangerie | Bakery | مخبز',
    germanText: 'die Bäckerei',
    article: 'die',
  },
  {
    id: '10',
    category: 'NOMS',
    frenchText: 'Bretzel',
    englishText: 'Pretzel',
    arabicText: 'بريتزل',
    sourceText: 'Bretzel | Pretzel | بريتزل',
    germanText: 'die Brezel',
    article: 'die',
  },
  {
    id: '11',
    category: 'NOMS',
    frenchText: 'Café (boisson)',
    englishText: 'Coffee',
    arabicText: 'قهوة',
    sourceText: 'Café (boisson) | Coffee | قهوة',
    germanText: 'der Kaffee',
    article: 'der',
  },
  {
    id: '12',
    category: 'NOMS',
    frenchText: 'Café (lieu)',
    englishText: 'Café / Coffee shop',
    arabicText: 'مقهى',
    sourceText: 'Café (lieu) | Café | مقهى',
    germanText: 'das Café',
    article: 'das',
  },
  {
    id: '13',
    category: 'NOMS',
    frenchText: 'Chat',
    englishText: 'Cat',
    arabicText: 'قطة',
    sourceText: 'Chat | Cat | قطة',
    germanText: 'die Katze',
    article: 'die',
  },
  {
    id: '14',
    category: 'NOMS',
    frenchText: 'Cheval',
    englishText: 'Horse',
    arabicText: 'حصان',
    sourceText: 'Cheval | Horse | حصان',
    germanText: 'das Pferd',
    article: 'das',
  },
  {
    id: '15',
    category: 'NOMS',
    frenchText: 'Chien',
    englishText: 'Dog',
    arabicText: 'كلب',
    sourceText: 'Chien | Dog | كلب',
    germanText: 'der Hund',
    article: 'der',
  },
  {
    id: '16',
    category: 'NOMS',
    frenchText: 'Eau',
    englishText: 'Water',
    arabicText: 'ماء',
    sourceText: 'Eau | Water | ماء',
    germanText: 'das Wasser',
    article: 'das',
  },
  {
    id: '17',
    category: 'NOMS',
    frenchText: 'Escalope',
    englishText: 'Cutlet / Schnitzel',
    arabicText: 'شرائحة لحم (شنitzel)',
    sourceText: 'Escalope | Schnitzel | شرائحة لحم',
    germanText: 'das Schnitzel',
    article: 'das',
  },
  {
    id: '18',
    category: 'NOMS',
    frenchText: 'Femme / Madame',
    englishText: 'Woman / Mrs.',
    arabicText: 'امرأة / سيدة',
    sourceText: 'Femme / Madame | Woman / Mrs. | امرأة / سيدة',
    germanText: 'die Frau',
    article: 'die',
  },
  {
    id: '19',
    category: 'NOMS',
    frenchText: 'Fête / Soirée',
    englishText: 'Party',
    arabicText: 'حفلة',
    sourceText: 'Fête / Soirée | Party | حفلة',
    germanText: 'die Party',
    article: 'die',
  },
  {
    id: '20',
    category: 'NOMS',
    frenchText: 'Fromage',
    englishText: 'Cheese',
    arabicText: 'جبن',
    sourceText: 'Fromage | Cheese | جبن',
    germanText: 'der Käse',
    article: 'der',
  },
  {
    id: '21',
    category: 'NOMS',
    frenchText: 'Gâteau',
    englishText: 'Cake',
    arabicText: 'كعكة / كيك',
    sourceText: 'Gâteau | Cake | كعكة',
    germanText: 'der Kuchen',
    article: 'der',
  },
  {
    id: '22',
    category: 'NOMS',
    frenchText: 'Homme / Mari',
    englishText: 'Man / Husband',
    arabicText: 'رجل / زوج',
    sourceText: 'Homme / Mari | Man / Husband | رجل / زوج',
    germanText: 'der Mann',
    article: 'der',
  },
  {
    id: '23',
    category: 'NOMS',
    frenchText: 'Lait',
    englishText: 'Milk',
    arabicText: 'حليب',
    sourceText: 'Lait | Milk | حليب',
    germanText: 'die Milch',
    article: 'die',
  },
  {
    id: '24',
    category: 'NOMS',
    frenchText: 'Parents',
    englishText: 'Parents',
    arabicText: 'والدان',
    sourceText: 'Parents | Parents | والدان',
    germanText: 'die Eltern',
    article: 'die (pluriel)',
    notes: '(pluriel)',
  },
  {
    id: '25',
    category: 'NOMS',
    frenchText: 'Pain',
    englishText: 'Bread',
    arabicText: 'خبز',
    sourceText: 'Pain | Bread | خبز',
    germanText: 'das Brot',
    article: 'das',
  },
  {
    id: '26',
    category: 'NOMS',
    frenchText: 'Professeur',
    englishText: 'Teacher',
    arabicText: 'أستاذ / معلم',
    sourceText: 'Professeur | Teacher | أستاذ',
    germanText: 'der Lehrer',
    article: 'der',
  },
  {
    id: '27',
    category: 'NOMS',
    frenchText: 'Restaurant',
    englishText: 'Restaurant',
    arabicText: 'مطعم',
    sourceText: 'Restaurant | Restaurant | مطعم',
    germanText: 'das Restaurant',
    article: 'das',
  },
  {
    id: '28',
    category: 'NOMS',
    frenchText: 'Sœur',
    englishText: 'Sister',
    arabicText: 'أخت',
    sourceText: 'Sœur | Sister | أخت',
    germanText: 'die Schwester',
    article: 'die',
  },
  {
    id: '29',
    category: 'NOMS',
    frenchText: 'Sucre',
    englishText: 'Sugar',
    arabicText: 'سكر',
    sourceText: 'Sucre | Sugar | سكر',
    germanText: 'der Zucker',
    article: 'der',
  },
  {
    id: '30',
    category: 'NOMS',
    frenchText: 'Travail',
    englishText: 'Work / Job',
    arabicText: 'عمل',
    sourceText: 'Travail | Work | عمل',
    germanText: 'die Arbeit',
    article: 'die',
  },
  {
    id: '31',
    category: 'NOMS',
    frenchText: 'Université',
    englishText: 'University',
    arabicText: 'جامعة',
    sourceText: 'Université | University | جامعة',
    germanText: 'die Universität',
    article: 'die',
  },
  {
    id: '32',
    category: 'NOMS',
    frenchText: 'Ville',
    englishText: 'City / Town',
    arabicText: 'مدينة',
    sourceText: 'Ville | City | مدينة',
    germanText: 'die Stadt',
    article: 'die',
  },

  // VERBES
  {
    id: '33',
    category: 'VERBES',
    frenchText: 'Aller',
    englishText: 'To go / walk',
    arabicText: 'ذهب / يذهب',
    sourceText: 'Aller | To go | ذهب',
    germanText: 'gehen',
  },
  {
    id: '34',
    category: 'VERBES',
    frenchText: 'Avoir',
    englishText: 'To have',
    arabicText: 'ملك / يملك',
    sourceText: 'Avoir | To have | يملك',
    germanText: 'haben',
  },
  {
    id: '35',
    category: 'VERBES',
    frenchText: 'Avoir besoin de',
    englishText: 'To need',
    arabicText: 'احتاج / يحتاج',
    sourceText: 'Avoir besoin de | To need | احتاج',
    germanText: 'brauchen',
  },
  {
    id: '36',
    category: 'VERBES',
    frenchText: 'Boire',
    englishText: 'To drink',
    arabicText: 'شرب / يشرب',
    sourceText: 'Boire | To drink | شرب',
    germanText: 'trinken',
  },
  {
    id: '37',
    category: 'VERBES',
    frenchText: 'Cuisiner',
    englishText: 'To cook',
    arabicText: 'طبخ / يطبخ',
    sourceText: 'Cuisiner | To cook | طبخ',
    germanText: 'kochen',
  },
  {
    id: '38',
    category: 'VERBES',
    frenchText: "Étudier (à l'université)",
    englishText: 'To study',
    arabicText: 'درس / يدرس',
    sourceText: "Étudier | To study | درس",
    germanText: 'studieren',
  },
  {
    id: '39',
    category: 'VERBES',
    frenchText: 'Faire',
    englishText: 'To do / make',
    arabicText: 'فعل / يفعل',
    sourceText: 'Faire | To do | فعل',
    germanText: 'machen',
  },
  {
    id: '40',
    category: 'VERBES',
    frenchText: 'Habiter',
    englishText: 'To live / reside',
    arabicText: 'سكن / يسكن',
    sourceText: 'Habiter | To live | سكن',
    germanText: 'wohnen',
  },
  {
    id: '41',
    category: 'VERBES',
    frenchText: 'Jouer',
    englishText: 'To play',
    arabicText: 'لعب / يلعب',
    sourceText: 'Jouer | To play | لعب',
    germanText: 'spielen',
  },
  {
    id: '42',
    category: 'VERBES',
    frenchText: 'Nager',
    englishText: 'To swim',
    arabicText: 'سبح / يسبح',
    sourceText: 'Nager | To swim | سبح',
    germanText: 'schwimmen',
  },
  {
    id: '43',
    category: 'VERBES',
    frenchText: 'Payer',
    englishText: 'To pay',
    arabicText: 'دفع / يدفع',
    sourceText: 'Payer | To pay | دفع',
    germanText: 'zahlen',
  },
  {
    id: '44',
    category: 'VERBES',
    frenchText: 'Rendre visite / Visiter',
    englishText: 'To visit',
    arabicText: 'زار / يزور',
    sourceText: 'Rendre visite | To visit | زار',
    germanText: 'besuchen',
  },
  {
    id: '45',
    category: 'VERBES',
    frenchText: 'Venir / Arriver',
    englishText: 'To come',
    arabicText: 'جاء / يأتي',
    sourceText: 'Venir | To come | جاء',
    germanText: 'kommen',
  },

  // ADJECTIFS & ADVERBES
  {
    id: '46',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'À droite',
    englishText: 'On the right',
    arabicText: 'على اليمين',
    sourceText: 'À droite | On the right | على اليمين',
    germanText: 'rechts',
  },
  {
    id: '47',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'À gauche',
    englishText: 'On the left',
    arabicText: 'على اليسار',
    sourceText: 'À gauche | On the left | على اليسار',
    germanText: 'links',
  },
  {
    id: '48',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Affamé',
    englishText: 'Hungry',
    arabicText: 'جائع',
    sourceText: 'Affamé | Hungry | جائع',
    germanText: 'hungrig',
  },
  {
    id: '49',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Amusant / Drôle',
    englishText: 'Funny / Amusing',
    arabicText: 'مضحك / ممتع',
    sourceText: 'Amusant | Funny | مضحك',
    germanText: 'lustig',
  },
  {
    id: '50',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Beau',
    englishText: 'Beautiful / Nice',
    arabicText: 'جميل',
    sourceText: 'Beau | Beautiful | جميل',
    germanText: 'schön',
  },
  {
    id: '51',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Bruyant / Fort',
    englishText: 'Loud',
    arabicText: 'صاخب / مرتفع',
    sourceText: 'Bruyant | Loud | صاخب',
    germanText: 'laut',
  },
  {
    id: '52',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Chaud',
    englishText: 'Warm / Hot',
    arabicText: 'دافئ / حار',
    sourceText: 'Chaud | Warm | دافئ',
    germanText: 'warm',
  },
  {
    id: '53',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Fatigué',
    englishText: 'Tired',
    arabicText: 'متعب',
    sourceText: 'Fatigué | Tired | متعب',
    germanText: 'müde',
  },
  {
    id: '54',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Gentil',
    englishText: 'Nice / Kind',
    arabicText: 'لطيف',
    sourceText: 'Gentil | Kind | لطيف',
    germanText: 'nett',
  },
  {
    id: '55',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Grand',
    englishText: 'Big / Tall',
    arabicText: 'كبير / طويل',
    sourceText: 'Grand | Big | كبير',
    germanText: 'groß',
  },
  {
    id: '56',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Ici',
    englishText: 'Here',
    arabicText: 'هنا',
    sourceText: 'Ici | Here | هنا',
    germanText: 'hier',
  },
  {
    id: '57',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Intéressant',
    englishText: 'Interesting',
    arabicText: 'ممتع / مثير للاهتمام',
    sourceText: 'Intéressant | Interesting | ممتع',
    germanText: 'interessant',
  },
  {
    id: '58',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Petit',
    englishText: 'Small / Short',
    arabicText: 'صغير',
    sourceText: 'Petit | Small | صغير',
    germanText: 'klein',
  },
  {
    id: '59',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Propre',
    englishText: 'Clean',
    arabicText: 'نظيف',
    sourceText: 'Propre | Clean | نظيف',
    germanText: 'sauber',
  },
  {
    id: '60',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Sportif',
    englishText: 'Sporty',
    arabicText: 'رياضي',
    sourceText: 'Sportif | Sporty | رياضي',
    germanText: 'sportlich',
  },
  {
    id: '61',
    category: 'ADJECTIFS_ADVERBES',
    frenchText: 'Très / Beaucoup',
    englishText: 'Very',
    arabicText: 'جداً / كثيراً',
    sourceText: 'Très | Very | جداً',
    germanText: 'sehr',
  },

  // EXPRESSIONS
  {
    id: '62',
    category: 'EXPRESSIONS',
    frenchText: "À l'étranger",
    englishText: 'Abroad',
    arabicText: 'في الخارج',
    sourceText: "À l'étranger | Abroad | في الخارج",
    germanText: 'im Ausland',
  },
  {
    id: '63',
    category: 'EXPRESSIONS',
    frenchText: 'À la maison (direction)',
    englishText: 'Homeward / To home',
    arabicText: 'إلى البيت',
    sourceText: 'À la maison | To home | إلى البيت',
    germanText: 'nach Hause',
  },
  {
    id: '64',
    category: 'EXPRESSIONS',
    frenchText: 'Ça va ?',
    englishText: 'How are you?',
    arabicText: 'كيف حالك؟',
    sourceText: 'Ça va ? | How are you? | كيف حالك؟',
    germanText: "wie geht's?",
  },
  {
    id: '65',
    category: 'EXPRESSIONS',
    frenchText: 'Désolé',
    englishText: 'Sorry',
    arabicText: 'آسف',
    sourceText: 'Désolé | Sorry | آسف',
    germanText: 'sorry',
  },
  {
    id: '66',
    category: 'EXPRESSIONS',
    frenchText: 'Enchanté',
    englishText: 'Pleased to meet you',
    arabicText: 'تشرفت بمعرفتك',
    sourceText: 'Enchanté | Nice to meet you | تشرفت بمعرفتك',
    germanText: 'freut mich',
  },
  {
    id: '67',
    category: 'EXPRESSIONS',
    frenchText: 'En retard',
    englishText: 'Late',
    arabicText: 'متأخر',
    sourceText: 'En retard | Late | متأخر',
    germanText: 'spät dran',
  },
  {
    id: '68',
    category: 'EXPRESSIONS',
    frenchText: 'Merci',
    englishText: 'Thank you',
    arabicText: 'شكراً',
    sourceText: 'Merci | Thank you | شكراً',
    germanText: 'danke',
  },
  {
    id: '69',
    category: 'EXPRESSIONS',
    frenchText: 'Prends soin de toi',
    englishText: 'Take care',
    arabicText: 'اعتني بنفسك',
    sourceText: 'Prends soin de toi | Take care | اعتني بنفسك',
    germanText: "mach's gut",
  },
  {
    id: '70',
    category: 'EXPRESSIONS',
    frenchText: 'Salut / Au revoir',
    englishText: 'Hello / Bye',
    arabicText: 'مرحباً / وداعاً',
    sourceText: 'Salut / Au revoir | Hello / Bye | مرحباً / وداعاً',
    germanText: 'hallo / tschüss',
  },
  {
    id: '71',
    category: 'EXPRESSIONS',
    frenchText: "S'il te plaît",
    englishText: 'Please',
    arabicText: 'من فضلك',
    sourceText: "S'il te plaît | Please | من فضلك",
    germanText: 'bitte',
  },
];
